# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: E2ETest
  displayName: E2E Tests
  jobs:
  - job: SetupScript
    steps:
    - script: |
        sudo apt update
        sudo apt install jq
      displayName: 'Install jq'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Connection to Pipeline resources for IoT Edge Config'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az extension add --name azure-iot
          az --version
          az account set -s $(AzureSubscriptionId)
      displayName: 'Set Azure resources'
        
  - job: LinuxE2ETests
    pool:
      vmImage: ubuntu-18.04
    steps: 
    - template: continuous-e2e.yml
    dependsOn: SetupScript
    condition: succeeded()

  - job: RaspberryPiE2ETests
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: continuous-e2e.yml
    dependsOn: SetupScript
    condition: succeeded()
  
