# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: E2ETest
  displayName: E2E Tests
  jobs:
  - job: SetupScript
    steps:
    - script: |
        sudo echo -e "\ndeb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/18.04/multiarch/prod bionic main" > /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt update
        sudo apt install jq
        sudo apt install tree -y
        sudo apt upgrade -y
        sudo apt install aziot-edge -y
      displayName: 'Install jq tree'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Connection to Pipeline resources for IoT Edge Config'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az upgrade
          az extension add --name azure-iot
          az --version
          az account set -s $(AzureSubscriptionId)
      displayName: 'Set Azure resources'
    
  - job: LinuxE2ETests
    pool:
      vmImage: ubuntu-18.04
    steps: 
    - template: continuous-e2e.yml
    dependsOn: SetupScript
    condition: succeeded()

  - job: RaspberryPiE2ETests
    pool:
      vmImage: ubuntu-18.04
    steps:
    - template: continuous-e2e.yml
    dependsOn: SetupScript
    condition: succeeded()
  
