# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: E2ETest
  displayName: E2E Tests
  jobs:
  - job: LinuxE2ETests
    pool:
      name: IoT-Devices-E2E
    steps: 
    - template: continuous-e2e-setup.yml
    - template: continuous-e2e-uninstalledge.yml
    - template: continuous-e2e.yml
    dependsOn: []
    condition: succeeded()

  - job: RaspberryPiE2ETests
    pool:
      name: Raspberry-Pi
    steps:
    - template: continuous-e2e-setup.yml
    - template: continuous-e2e-uninstalledge.yml
    - template: continuous-e2e.yml
    dependsOn:
    - LinuxE2ETests
    condition: succeeded()

  - job: Ubuntu1804E2ETests
    pool:
      vmImage: ubuntu-18.04
    steps: 
    - template: continuous-e2e-setup.yml
    - template: continuous-e2e-uninstalledge.yml
    - template: continuous-e2e.yml
    dependsOn:
    - RaspberryPiE2ETests
    condition: succeeded()

  - job: Ubuntu2004E2ETests
    pool:
      vmImage: ubuntu-20.04
    steps: 
    - template: continuous-e2e-setup.yml
    - template: continuous-e2e-uninstalledge.yml
    - template: continuous-e2e.yml
    dependsOn:
    - Ubuntu1804E2ETests
    condition: succeeded()
  
