# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: UnitTest
  displayName: Unit Tests
  jobs:  
  - job: LinuxUnitTests
    pool:
      vmImage: ubuntu-18.04
    steps: 
    - template: linux/continuous-linux.yml

  - job: RaspberryPiUnitTests
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: raspi/continuous-raspi.yml

  - job: GithubRelease
    dependsOn:
      - LinuxUnitTests
      - RaspberryPiUnitTests
    condition: and(succeeded('LinuxUnitTests'), succeeded('RaspberryPiUnitTests')) 
    steps:
    - script: |  
        mkdir dest
        cp src/*.sh dest/
        chmod +x tools/generate_sigs.sh
        cd dest
        ../tools/generate_sigs.sh
        cd ..
      displayName: Create dest/ directory
    - task: GitHubRelease@1
      displayName: 'GitHub release (create) RC'
      inputs:
        gitHubConnection: 'github.com_cindydeng1998'
        tagPattern: '^v?[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$'
        assets: 'dest/*.sh'
        isDraft: true
    - task: GitHubRelease@1
      displayName: 'GitHub release (create)'
      inputs:
        gitHubConnection: 'github.com_cindydeng1998'
        tagPattern: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
        assets: 'dest/*.sh'
        isDraft: true
