# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: PERFTests
  displayName: Performance Tests
  jobs:
  - job: LinuxE2ETests
    pool:
      name: IoT-Devices-E2E
    steps: 
    - template: continuous-e2e-setup.yml
    - template: continuous-e2e-uninstalledge.yml
    - template: continuous-perf.yml
    dependsOn: []
    condition: succeeded()

  - job: RaspberryPiPerfTests
    pool:
      name: Raspberry-Pi
    steps:
    - template: continuous-e2e-setup.yml
    - template: continuous-e2e-uninstalledge.yml
    - template: continuous-perf.yml
    dependsOn: []
    condition: succeeded()

  - job: Ubuntu1804PerfTests
    pool:
      vmImage: ubuntu-18.04
    steps: 
    - template: continuous-e2e-setup.yml
    - template: continuous-perf.yml
    dependsOn: []
    condition: succeeded()

  - job: Ubuntu2004PerfTests
    pool:
      vmImage: ubuntu-20.04
    steps: 
    - template: continuous-e2e-setup.yml
    - template: continuous-perf.yml
    dependsOn: []
    condition: succeeded()