# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

-jobs:
  - job: Setup Script
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
  
  - job: Linux Unit Tests
    pool:
      vmImage: ubuntu-18.04
    steps: 
    - template: linux/continuous-linux.yml

  - job: Raspberry Pi Unit Tests
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: raspi/continuous-raspi.yml

    
